version: '3'
services:
  der:
    build: ./doc_event_role
    stdin_open: true
    tty: true
    ports:
      - 8888:8888
      - 6006:6006
    command: "/bin/bash"
    environment:
      NVIDIA_VISIBLE_DEVICES: 0
      CUDA_VISIBLE_DEVICES: 0
    ulimits:
      memlock: -1
    shm_size: '16gb'
    volumes:
      - ./doc_event_role:/der
    ipc: "host"
