python gen_seq_tag_pairs.py --div train --template_type attack
python gen_seq_tag_pairs.py --div dev --template_type attack
python gen_seq_tag_pairs.py --div test --template_type attack
python gen_seq_tag_pairs.py --div train --template_type kidnapping
python gen_seq_tag_pairs.py --div dev --template_type kidnapping
python gen_seq_tag_pairs.py --div test --template_type kidnapping
python gen_seq_tag_pairs.py --div train --template_type bombing
python gen_seq_tag_pairs.py --div dev --template_type bombing
python gen_seq_tag_pairs.py --div test --template_type bombing